### ISSUE TITLE
Doesnt make collection

### ISSUE THREAD

**Issue by Cuckkster** [upgradeQ/OSU-STREAM-DETECTOR#3]
Doesnt make collection even with -c added in the command. For example (-a 170 -b 180 -c -i) does not make a collection for songs.

**Comment by upgradeQ** [comment]
Hello @Cuckkster , does it generates  `Stream maps[140-9999] <timestamp>.txt` if you run it without arguments? Also it's worth mentioning that there is configuration file created after first run, maybe there is something wrong with it? It's located in your python path in `Lib/site-packages/stream_detector.ini`. I did run `osustreams -a 170 -b 180 -c -i` in command line and collection has been generated in `osu!` client.

**Comment by Cuckkster** [comment]
@upgradeQ it tells me this with 
![image](https://user-images.githubusercontent.com/74056536/98485668-d9706980-21cc-11eb-9baa-b256c46bd3ba.png) im not sure what this really means but if you can help me decipher that would be amazing!

**Comment by Cuckkster** [comment]
but with that being said i even changed the path for the .ini file and it would not run at all if i tried to make the path into my regular osu! file instead of songs.

**Comment by upgradeQ** [comment]
@Cuckkster it breaks because parsing of the .osu file function has not expected that to happen. Update to new version `python -m pip install -U osustreams`, that should handle this error. In screenshot I see that there is      

> Signals XenjeS` 10 MHz 27%

That means that path setup is correct.

**Comment by upgradeQ** [comment]
If something is broken again please reopen issue
